import type { Metadata } from 'next';
import { verdanaNormal } from '@/fonts/font';

export const metadata: Metadata = {
  title: 'Get Houses',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={verdanaNormal.className}>{children}</body>
    </html>
  );
}
